require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

$RNFirebaseDisableSPM = true
$RNFirebaseAsStaticFramework = true

prepare_react_native_project!

use_frameworks! :linkage => :static
use_modular_headers!

target 'syilReact' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']

          unless config.build_settings[
            'GCC_PREPROCESSOR_DEFINITIONS'
          ].include?('FMT_USE_CONSTEXPR=0')
            config.build_settings[
              'GCC_PREPROCESSOR_DEFINITIONS'
            ] << 'FMT_USE_CONSTEXPR=0'
          end
        end
      end
    end
  end
end